# Generated by Django 4.2.1 on 2023-11-04 15:30

import InviteManagement.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('workspace_type', models.CharField(choices=[('Project', 'Project')], max_length=15)),
                ('invite_params', models.JSONField(default=InviteManagement.models.default_json)),
                ('workspace_id', models.IntegerField()),
                ('email_sent', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('reminder', models.BooleanField(default=False)),
                ('reminder_period', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('invite_expiry', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('reminder_threshold', models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3)])),
                ('invite_host', models.ForeignKey(on_delete=models.SET(InviteManagement.models.get_sentinel_user), related_name='invitor_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
