# Generated by Django 4.2.1 on 2023-11-25 11:05

from django.db import migrations, models
import uuid



class Migration(migrations.Migration):

    dependencies = [
        ('InviteManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invite_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
