# Generated by Django 4.2.1 on 2024-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InviteManagement', '0003_alter_invite_invite_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invite_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Declined'), (4, 'Expired'), (5, 'Cancelled')], default=1),
        ),
    ]
