# Generated by Django 4.2.1 on 2024-08-24 20:02

import InviteManagement.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InviteManagement', '0004_invite_invite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_host',
            field=models.ForeignKey(on_delete=models.SET(InviteManagement.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
