# Generated by Django 4.2.1 on 2023-06-28 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0002_project_budget_project_budget_allocated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_access_level', models.IntegerField(choices=[('2', 'partner'), ('1', 'collaborator'), ('0', 'view only access')], default=0)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_partner_projectid', to='Projects.project')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_partner_userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
