# Generated by Django 4.2.1 on 2023-11-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_access_level', models.IntegerField(choices=[('3', 'Owner'), ('2', 'partner'), ('1', 'collaborator'), ('0', 'view only access')], default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_partner_projectid', to='Projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_partner_userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
