# Generated by Django 4.2.1 on 2023-06-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectPartnerManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpartner',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectpartner',
            old_name='userId',
            new_name='user',
        ),
    ]
