# Generated by Django 4.2.1 on 2023-07-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectPartnerManagement', '0002_rename_project_id_projectpartner_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpartner',
            name='user_access_level',
            field=models.IntegerField(choices=[('3', 'Owner'), ('2', 'partner'), ('1', 'collaborator'), ('0', 'view only access')], default=0),
        ),
    ]
