# Generated by Django 4.2.1 on 2023-11-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('objective', models.TextField(max_length=1024)),
                ('description', models.TextField(max_length=2048)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('estimated_cost', models.IntegerField()),
                ('priority', models.CharField(choices=[('Critical', 'critical'), ('High', 'High priority'), ('medium', 'Medium priority'), ('low', 'Low Priority')], max_length=10)),
                ('project_currency', models.CharField(choices=[('KES', 'Kenya Shillings'), ('USD', 'United States Dollar'), ('GBP', 'Sterling Pound'), ('EUR', 'Euro'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandese Franc'), ('CDF', 'Congolese Franc')], default='KES', max_length=10)),
                ('status', models.CharField(choices=[('To-do', 'To-Do'), ('progress', 'In Progress'), ('blocked', 'Blocked'), ('on hold', 'Paused'), ('done', 'Done'), ('cancel', 'Cancel')], default='To-do', max_length=10)),
                ('progress', models.FloatField(default=0)),
                ('budget', models.IntegerField(default=1)),
                ('budget_allocated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('objective_achieved', models.BooleanField(default=False)),
                ('estimated_start_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_end_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_timeline', models.CharField(blank=True, max_length=256, null=True)),
                ('estimated_income', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('actual_cost', models.IntegerField(blank=True, null=True)),
                ('actual_income', models.IntegerField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, max_length=2048, null=True)),
                ('blocked_reason', models.TextField(blank=True, max_length=2048, null=True)),
                ('review', models.TextField(blank=True, max_length=2048, null=True)),
            ],
        ),
    ]
