# Generated by Django 4.2.1 on 2023-06-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_timeline', models.DurationField()),
                ('estimated_cost', models.IntegerField()),
                ('estimated_income', models.IntegerField(null=True)),
                ('estimated_start_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('To-do', 'To-Do'), ('progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancel', 'Cancel')], max_length=10)),
                ('priority', models.CharField(choices=[('Critical', 'critical'), ('High', 'High priority'), ('medium', 'Medium priority'), ('low', 'Low Priority')], max_length=10)),
            ],
        ),
    ]
