# Generated by Django 4.2.1 on 2023-06-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
