# Generated by Django 4.2.1 on 2023-07-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_project_budget_project_budget_allocated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
