# Generated by Django 4.2.1 on 2023-07-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_project_cancel_reason_project_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blocked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
