# Generated by Django 4.2.1 on 2023-07-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_project_blocked_reason_project_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_currency',
            field=models.CharField(choices=[('KES', 'Kenya Shillings'), ('USD', 'United States Dollar'), ('GBP', 'Sterling Pound'), ('EUR', 'Euro'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandese Franc'), ('CDF', 'Congolese Franc')], default='KES', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='blocked_reason',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cancel_reason',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='review',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('To-do', 'To-Do'), ('progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancel', 'Cancel')], default='To-do', max_length=10),
        ),
    ]
