# Generated by Django 4.2.1 on 2023-07-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_project_actual_cost_project_actual_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(default='try', max_length=1024),
            preserve_default=False,
        ),
    ]
