# Generated by Django 4.2.1 on 2023-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_project_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='objective_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
