# Generated by Django 4.2.1 on 2023-07-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_project_objective_achieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('To-do', 'To-Do'), ('progress', 'In Progress'), ('blocked', 'Blocked'), ('on hold', 'Paused'), ('done', 'Done'), ('cancel', 'Cancel')], default='To-do', max_length=10),
        ),
    ]
