# Generated by Django 4.2.1 on 2023-07-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_timeline',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
