# Generated by Django 4.2.1 on 2023-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_project_estimated_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_timeline',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
